import { neon } from '@neondatabase/serverless';
import { SavedIdea, ResearchPackage } from './types';

function getDb() {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error('DATABASE_URL is not set in environment variables');
  }
  return neon(databaseUrl);
}

export async function initDb(): Promise<void> {
  const sql = getDb();
  await sql`
    CREATE TABLE IF NOT EXISTS ideas (
      id TEXT PRIMARY KEY,
      topic TEXT NOT NULL,
      style TEXT,
      top_title TEXT,
      research_data TEXT NOT NULL,
      auto_generated BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `;
}

interface IdeaRow {
  id: string;
  topic: string;
  style: string | null;
  top_title: string | null;
  research_data: string;
  auto_generated: boolean;
  created_at: string;
}

function rowToIdea(row: IdeaRow): SavedIdea {
  const researchData = typeof row.research_data === 'string'
    ? JSON.parse(row.research_data)
    : row.research_data;
  return {
    ...row,
    research_data: researchData,
    auto_generated: Boolean(row.auto_generated),
  };
}

export async function saveIdea(
  id: string,
  topic: string,
  style: string | null,
  researchData: ResearchPackage,
  autoGenerated: boolean = false
): Promise<void> {
  const sql = getDb();
  await initDb();
  const topTitle = researchData.viralConcept?.titles?.[0] || topic;
  await sql`
    INSERT INTO ideas (id, topic, style, top_title, research_data, auto_generated)
    VALUES (${id}, ${topic}, ${style}, ${topTitle}, ${JSON.stringify(researchData)}, ${autoGenerated})
  `;
}

export async function getAllIdeas(search?: string): Promise<SavedIdea[]> {
  const sql = getDb();
  await initDb();
  let rows: IdeaRow[];
  if (search) {
    const pattern = `%${search}%`;
    rows = (await sql`
      SELECT * FROM ideas WHERE topic ILIKE ${pattern} OR top_title ILIKE ${pattern} ORDER BY created_at DESC
    `) as unknown as IdeaRow[];
  } else {
    rows = (await sql`
      SELECT * FROM ideas ORDER BY created_at DESC
    `) as unknown as IdeaRow[];
  }
  return rows.map(rowToIdea);
}

export async function getIdeaById(id: string): Promise<SavedIdea | null> {
  const sql = getDb();
  await initDb();
  const rows = (await sql`
    SELECT * FROM ideas WHERE id = ${id}
  `) as unknown as IdeaRow[];
  return rows.length > 0 ? rowToIdea(rows[0]) : null;
}

export async function deleteIdea(id: string): Promise<boolean> {
  const sql = getDb();
  await initDb();
  const result = await sql`DELETE FROM ideas WHERE id = ${id}`;
  return result.length >= 0;
}
